import type { Movie } from '../model/types'

export const MOCK_MOVIES: Movie[] = [
  {
    id: 'movie-1',
    title: 'O Último Refúgio',
    originalTitle: 'The Last Haven',
    posterUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=600&q=80',
    rating: 8.4,
    votesCount: 3420,
    genres: ['Ação', 'Thriller'],
    year: 2023,
    ageRating: '14+',
    cast: ['Keanu Reeves', 'Zoe Saldana', 'John Boyega'],
    director: 'Denis Villeneuve',
    durationMinutes: 142,
    synopsis: 'Em um mundo pós-colapso, um veterano protege o último santuário da humanidade contra forças implacáveis.',
    popularity: 98,
  },
  {
    id: 'movie-2',
    title: 'Estrelas de Outono',
    originalTitle: 'Autumn Stars',
    posterUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80',
    rating: 7.9,
    votesCount: 2190,
    genres: ['Drama', 'Romance'],
    year: 2021,
    ageRating: '12+',
    cast: ['Emma Stone', 'Ryan Gosling', 'Rachel McAdams'],
    director: 'Damien Chazelle',
    durationMinutes: 128,
    synopsis: 'Dois artistas em encruzilhadas emocionais se reencontram em uma pequena cidade costeira durante o outono.',
    popularity: 84,
  },
  {
    id: 'movie-3',
    title: 'Código Noturno',
    originalTitle: 'Night Code',
    posterUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=600&q=80',
    rating: 8.1,
    votesCount: 4120,
    genres: ['Ficção Científica', 'Thriller'],
    year: 2024,
    ageRating: '16+',
    cast: ['Cillian Murphy', 'Florence Pugh', 'Rami Malek'],
    director: 'Christopher Nolan',
    durationMinutes: 156,
    synopsis: 'Uma inteligência artificial secreta envia mensagens codificadas que preveem incidentes globais antes de acontecerem.',
    popularity: 95,
  },
  {
    id: 'movie-4',
    title: 'A Dança do Silêncio',
    originalTitle: 'Dance of Silence',
    posterUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80',
    rating: 8.6,
    votesCount: 5200,
    genres: ['Romance', 'Drama'],
    year: 2022,
    ageRating: '10+',
    cast: ['Timothée Chalamet', 'Saoirse Ronan', 'Paul Mescal'],
    director: 'Greta Gerwig',
    durationMinutes: 119,
    synopsis: 'Uma pianista prodígio com perda auditiva progressiva descobre uma nova forma de sentir e expressar música.',
    popularity: 91,
  },
  {
    id: 'movie-5',
    title: 'Horizonte Perdido',
    originalTitle: 'Lost Horizon',
    posterUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80',
    rating: 8.0,
    votesCount: 3870,
    genres: ['Ficção Científica', 'Ação'],
    year: 2023,
    ageRating: '14+',
    cast: ['Pedro Pascal', 'Oscar Isaac', 'Ana de Armas'],
    director: 'Alfonso Cuarón',
    durationMinutes: 135,
    synopsis: 'Exploradores espaciais descobrem um planeta desabitado que espelha exatamente a Terra em uma era passada.',
    popularity: 89,
  },
  {
    id: 'movie-6',
    title: 'Sombras do Amanhã',
    originalTitle: 'Shadows of Tomorrow',
    posterUrl: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=600&q=80',
    rating: 7.5,
    votesCount: 1840,
    genres: ['Thriller', 'Terror'],
    year: 2020,
    ageRating: '16+',
    cast: ['Jake Gyllenhaal', 'Hugh Jackman', 'Rebecca Ferguson'],
    director: 'David Fincher',
    durationMinutes: 122,
    synopsis: 'Um detetive investiga desaparecimentos em uma metrópole chuvosa onde a linha entre paranóia e realidade desaparece.',
    popularity: 76,
  },
  {
    id: 'movie-7',
    title: 'Ecos da Cidade',
    originalTitle: 'City Echoes',
    posterUrl: 'https://images.unsplash.com/photo-1477959858617-67f30bc75b82?auto=format&fit=crop&w=600&q=80',
    rating: 8.3,
    votesCount: 1650,
    genres: ['Documentário'],
    year: 2019,
    ageRating: 'L',
    cast: ['Wagner Moura', 'David Attenborough'],
    director: 'Fernando Meirelles',
    durationMinutes: 98,
    synopsis: 'Um olhar poético e revelador sobre as histórias ocultas e a arquitetura humana que pulsam sob o concreto.',
    popularity: 70,
  },
  {
    id: 'movie-8',
    title: 'Além do Horizonte',
    originalTitle: 'Beyond the Horizon',
    posterUrl: 'https://images.unsplash.com/photo-1518173946687-a4c8a383392e?auto=format&fit=crop&w=600&q=80',
    rating: 8.2,
    votesCount: 2980,
    genres: ['Drama', 'Ação'],
    year: 2024,
    ageRating: '12+',
    cast: ['Leonardo DiCaprio', 'Brad Pitt', 'Margot Robbie'],
    director: 'Martin Scorsese',
    durationMinutes: 168,
    synopsis: 'Dois pioneiros da aviação arriscam tudo em uma expedição pioneira sem volta pela cordilheira dos Andes.',
    popularity: 93,
  },
  {
    id: 'movie-9',
    title: 'Vila dos Sonhos',
    originalTitle: 'Dream Village',
    posterUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80',
    rating: 8.7,
    votesCount: 4500,
    genres: ['Animação', 'Comédia'],
    year: 2023,
    ageRating: 'L',
    cast: ['Tom Hanks', 'Steve Carell', 'Awkwafina'],
    director: 'Pete Docter',
    durationMinutes: 104,
    synopsis: 'Criaturas mágicas que constroem os sonhos dos humanos enfrentam uma crise cômica quando o gerador de pesadelos pifa.',
    popularity: 88,
  },
  {
    id: 'movie-10',
    title: 'O Enigma de Praga',
    originalTitle: 'The Prague Enigma',
    posterUrl: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=600&q=80',
    rating: 7.8,
    votesCount: 2310,
    genres: ['Thriller', 'Ação'],
    year: 2018,
    ageRating: '16+',
    cast: ['Daniel Craig', 'Eva Green', 'Mads Mikkelsen'],
    director: 'Sam Mendes',
    durationMinutes: 130,
    synopsis: 'Um criptógrafo internacional descobre um manuscrito medieval que desencadeia uma perseguição mortal pelas pontes de Praga.',
    popularity: 79,
  },
  {
    id: 'movie-11',
    title: 'Risadas em Família',
    originalTitle: 'Family Laughs',
    posterUrl: 'https://images.unsplash.com/photo-1514306191717-452ec28c7814?auto=format&fit=crop&w=600&q=80',
    rating: 6.9,
    votesCount: 1420,
    genres: ['Comédia'],
    year: 2022,
    ageRating: '10+',
    cast: ['Paul Rudd', 'Tina Fey', 'Jason Sudeikis'],
    director: 'Judd Apatow',
    durationMinutes: 110,
    synopsis: 'Uma viagem de férias que tinha tudo para dar errado acaba unindo três gerações de uma família excêntrica.',
    popularity: 65,
  },
  {
    id: 'movie-12',
    title: 'A Casa na Colina Escura',
    originalTitle: 'The House on Dark Hill',
    posterUrl: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=600&q=80',
    rating: 7.2,
    votesCount: 1980,
    genres: ['Terror', 'Thriller'],
    year: 2021,
    ageRating: '18+',
    cast: ['Toni Collette', 'Bill Skarsgård', 'Anya Taylor-Joy'],
    director: 'Ari Aster',
    durationMinutes: 127,
    synopsis: 'Uma restauradora de arte se muda para um casarão isolado e descobre pinturas que parecem observar seus passos.',
    popularity: 74,
  },
  {
    id: 'movie-13',
    title: 'Planeta Selvagem',
    originalTitle: 'Wild Earth',
    posterUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
    rating: 9.1,
    votesCount: 6800,
    genres: ['Documentário'],
    year: 2020,
    ageRating: 'L',
    cast: ['David Attenborough', 'Sigourney Weaver'],
    director: 'Alastair Fothergill',
    durationMinutes: 115,
    synopsis: 'Uma jornada cinematográfica nunca antes vista pelos habitats mais remotos e intocados da Terra.',
    popularity: 96,
  },
  {
    id: 'movie-14',
    title: 'Operação Crepúsculo',
    originalTitle: 'Twilight Protocol',
    posterUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80',
    rating: 8.5,
    votesCount: 3900,
    genres: ['Ação', 'Ficção Científica'],
    year: 2024,
    ageRating: '14+',
    cast: ['Tom Cruise', 'Emily Blunt', 'Idris Elba'],
    director: 'Doug Liman',
    durationMinutes: 138,
    synopsis: 'Agentes de elite precisam sincronizar saltos temporais em minutos para evitar um ataque nuclear no futuro.',
    popularity: 94,
  },
  {
    id: 'movie-15',
    title: 'O Reino das Sombras',
    originalTitle: 'Shadow Kingdom',
    posterUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80',
    rating: 8.8,
    votesCount: 5120,
    genres: ['Animação', 'Ação'],
    year: 2023,
    ageRating: '10+',
    cast: ['Zendaya', 'Shameik Moore', 'Hailee Steinfeld'],
    director: 'Joaquim Dos Santos',
    durationMinutes: 140,
    synopsis: 'Um jovem guerreiro atravessa dimensões pintadas à mão para resgatar sua ancestralidade esquecida.',
    popularity: 97,
  },
  {
    id: 'movie-16',
    title: 'Cartas para Ontem',
    originalTitle: 'Letters to Yesterday',
    posterUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=600&q=80',
    rating: 7.7,
    votesCount: 1540,
    genres: ['Romance', 'Drama'],
    year: 2017,
    ageRating: '12+',
    cast: ['Rachel McAdams', 'Domhnall Gleeson', 'Bill Nighy'],
    director: 'Richard Curtis',
    durationMinutes: 123,
    synopsis: 'Uma caixa de correio mágica conecta duas pessoas vivendo na mesma casa com 10 anos de diferença.',
    popularity: 72,
  },
]
